name: ml-nutrition-tutorial
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=2.4.1
  - blas=1.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - certifi=2024.2.2
  - charset-normalizer=2.0.4
  - comm=0.2.2
  - contourpy=1.2.0
  - cycler=0.11.0
  - debugpy=1.8.1
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - filelock=3.13.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - idna=3.4
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=1.2.0
  - jpeg=9e
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - kiwisolver=1.4.4
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcxx=16.0.6
  - libdeflate=1.8
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libjpeg-turbo=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsodium=1.0.18
  - libsqlite=3.45.2
  - libtiff=4.4.0
  - libwebp-base=1.3.2
  - libzlib=1.2.13
  - llvm-openmp=18.1.2
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.4.20240210
  - nest-asyncio=1.6.0
  - networkx=3.1
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.4.0
  - openssl=3.2.1
  - packaging=24.0
  - pandas=2.2.1
  - parso=0.8.3
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=24.0
  - platformdirs=4.2.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.9.0
  - python-tzdata=2023.3
  - python_abi=3.12
  - pytorch=2.2.1
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - readline=8.2
  - requests=2.31.0
  - scikit-learn=1.4.1.post1
  - scipy=1.12.0
  - setuptools=69.2.0
  - shellcheck=0.7.2
  - six=1.16.0
  - stack_data=0.6.2
  - sympy=1.12
  - tbb=2021.8.0
  - threadpoolctl=2.2.0
  - tk=8.6.13
  - torchaudio=2.2.1
  - torchvision=0.17.1
  - tornado=6.4
  - traitlets=5.14.2
  - typing_extensions=4.10.0
  - tzdata=2024a
  - urllib3=2.1.0
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.2
